In [ ]:
# from google.colab import drive

# # Try unmounting first to reset any existing session.
# drive.flush_and_unmount()
# print('Drive unmounted.')

# Now remount, granting all necessary permissions during the prompt.
# drive.mount('/content/drive', force_remount=True)
# print('Drive mounted successfully!')

# !cp /content/drive/MyDrive/Automobile.csv /content/

Drive unmounted.


In [ ]:
!ls

Automobile.csv	sample_data


In [ ]:
'''1. Loading a CSV File & Basic Exploration
Given a CSV file named "Automobile.csv":
Task
Write Python code to:
Load the CSV file into a Pandas DataFrame.
Display the first 30 rows.
Print column names.
Print No of Rows & Columns
Find the Data Types of every column & check if there are any mismatch
What are the minimum & maximum price of the car & state fuel type they belong to
List all the unique engine types
Find the horsepower range
What is the average mpg in cities & highway. Which is better?
What are the different Automobile makes present & which has maximum count?
'''

import pandas as pd
df=pd.read_csv('Automobile.csv')
print("First 30 rows")
print(df.head(30))
print("-----------------------------------------------------")
print("columns")
print(df.columns)
print("-----------------------------------------------------")
print("No of Rows & Columns")
print(df.shape)
print("-----------------------------------------------------")
print("Data Types")
print(df.dtypes)
print("-----------------------------------------------------")
print("Minimum Price")
print(df['price'].min())
print("Maximum Price")
print(df['price'].max())
print("-----------------------------------------------------")
print("Unique Engine Types")
print(df['fuel_type'].unique())
print("-----------------------------------------------------")
print("Horsepower Range")
print(df['horsepower'].min())
print(df['horsepower'].max())
print("-----------------------------------------------------")
print("Average MPG in Cities")
print(df['city_mpg'].mean())
print("Average MPG in Highway")
print(df['highway_mpg'].mean())
print("-----------------------------------------------------")



First 30 rows
    symboling  normalized_losses         make fuel_type aspiration  \
0           3                168  alfa-romero       gas        std   
1           3                168  alfa-romero       gas        std   
2           1                168  alfa-romero       gas        std   
3           2                164         audi       gas        std   
4           2                164         audi       gas        std   
5           2                161         audi       gas        std   
6           1                158         audi       gas        std   
7           1                168         audi       gas        std   
8           1                158         audi       gas      turbo   
9           2                192          bmw       gas        std   
10          0                192          bmw       gas        std   
11          0                188          bmw       gas        std   
12          0                188          bmw       gas        std   
13    

In [ ]:
'''2. Accessing Data with .loc[]
Using the following DataFrame:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Task
Retrieve the row where Name == "Charlie" using .loc[].
Select only the Age and Score columns for "Alice" and "Bob" using .loc[].
'''
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
print(df[df["Name"] == "Charlie"])
print(df.loc[df["Name"].isin(["Alice", "Bob"]), ["Age", "Score"]])

      Name  Age  Score
2  Charlie   22     78
   Age  Score
0   24     85
1   27     90


In [ ]:
'''3. Accessing Data with .iloc[]
Using the same DataFrame from Question 2, write code to:
Retrieve the second row using .iloc[].
Extract the last two rows using .iloc[].'''
print(df.iloc[1])
print(df.iloc[-2:])


Name     Bob
Age       27
Score     90
Name: 1, dtype: object
      Name  Age  Score
2  Charlie   22     78
3    David   32     88


In [ ]:
'''4. Filtering Rows Based on Conditions
Using the following DataFrame:
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
Task
Write a Pandas command to:
Select only IT employees.
Select employees with a salary greater than 55,000.
'''
import pandas as pd
df = pd.DataFrame({
    "Employee": ["John", "Alice", "Bob", "David"],
    "Salary": [50000, 60000, 55000, 65000],
    "Department": ["IT", "HR", "IT", "Finance"]
})
print(df[df["Department"]=="IT"])
print(df[df["Salary"]>55000])


  Employee  Salary Department
0     John   50000         IT
2      Bob   55000         IT
  Employee  Salary Department
1    Alice   60000         HR
3    David   65000    Finance


In [ ]:
'''5. Applying Functions to a Column
Using the following DataFrame:
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
Task
Write a function that:
Converts marks below 50 to "Fail", and 50 or above to "Pass".
Apply this function to the "Marks" column and create a new column "Result".
'''
import pandas as pd
df = pd.DataFrame({
    "Student": ["A", "B", "C", "D"],
    "Marks": [45, 78, 62, 90]
})
df["Result"]=(df["Marks"]>=50 ).replace({True:"Pass",False:"Fail"})
print(df)

  Student  Marks Result
0       A     45   Fail
1       B     78   Pass
2       C     62   Pass
3       D     90   Pass


In [ ]:
'''6. NumPy - Creating and Reshaping Arrays
Write Python code to:
Create a NumPy array with values from 1 to 12.
Reshape it into a 3x4 matrix.
'''
import numpy as np
arr=np.arange(1,13)
arr=arr.reshape(3,4)
print(arr)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
'''7. NumPy - Broadcasting & Element-wise Operations
You are given the following NumPy arrays:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
Task
Perform:
Element-wise multiplication of a and b.
Add 5 to each element of a using broadcasting.
'''
import numpy as np
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print(a,b)
print("Addition",a+b)
a=a+5
b=b+5
print("values of A,B After broadcasting",a,b)


[1 2 3] [10 20 30]
Addition [11 22 33]
values of A,B After broadcasting [6 7 8] [15 25 35]


In [ ]:
'''8. Finding Maximum and Minimum Values in a NumPy Array
Given:
arr = np.array([[3, 7, 2], [4, 9, 6]])
Task
Find the maximum value in the entire array.
Find the minimum value in each row.
'''
import numpy as np
arr = np.array([[3, 7, 2], [4, 9, 6]])
print("Minimum:",np.min(arr,axis=1))
print("Maximum:",arr.max())


Minimum: [2 4]
Maximum: 9


In [ ]:
'''9. Grouping & Aggregation in Pandas
You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Task
Write a Pandas command to:
Group the DataFrame by "Department" and calculate the average salary per department.
'''
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
print(df.groupby(["Department"])["Salary"].mean())


Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [ ]:
'''10. Sorting a DataFrame
Given the following DataFrame:
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
Task
Sort the DataFrame by Population in descending order.
'''
import pandas as pd
df = pd.DataFrame({
    "City": ["New York", "Los Angeles", "Chicago", "Houston"],
    "Population": [8419600, 3980400, 2716000, 2328000]
})
print(df.sort_values('Population',ascending=False))



          City  Population
0     New York     8419600
1  Los Angeles     3980400
2      Chicago     2716000
3      Houston     2328000


In [ ]:
'''11. Multi-Indexing in Pandas
You are given the following DataFrame:
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
Task
Retrieve the sales value for City A in the South Region using multi-indexing.'''
import pandas as pd
data = {
    "Region": ["North", "North", "South", "South", "East", "East"],
    "City": ["A", "B", "A", "B", "A", "B"],
    "Sales": [200, 150, 180, 220, 300, 250]
}
df = pd.DataFrame(data).set_index(["Region", "City"])
print(df.loc[("South","A"),"Sales"])

180


In [ ]:
'''12. Creating a DataFrame from a NumPy Array
Generate a 5x4 NumPy array with random integers between 10 and 99 and convert it into a Pandas DataFrame with column names ["A", "B", "C", "D"].
'''
import numpy as np
arr=np.random.randint(10,100,size=(5,4))
df=pd.DataFrame(arr,columns=["A","B","C","D"])
print(df)


    A   B   C   D
0  54  85  86  75
1  76  66  52  76
2  64  46  49  68
3  84  69  77  52
4  39  30  75  66


In [ ]:
'''13. Conditional Column Update
Given the following DataFrame:
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
Task
Write a one-liner Pandas command to set "Marks" to 0 for students whose "Attendance" is less than 60.
'''
import pandas as pd
df = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Marks": [88, 45, 76, 90],
    "Attendance": [85, 50, 90, 60]
})
df.loc[df["Attendance"]<60 ,"Marks"]=0
print(df)


   Student  Marks  Attendance
0    Alice     88          85
1      Bob      0          50
2  Charlie     76          90
3    David     90          60


In [31]:
'''14. Advanced Filtering
From a CSV file "employees.csv" with columns:
EmployeeID, Department, Salary, Experience (in years).
Note: You should create “employees.csv” & perform the below task
Task
Write a Pandas query to:
Select employees from "IT" or "Finance" department
Having Salary > 60,000
AND at least 5 years of experience
'''
data = {
    "EmployeeID": [1, 2, 3, 4, 5, 6, 7],
    "Department": ["IT", "HR", "Finance", "IT", "HR", "Finance", "IT"],
    "Salary": [70000, 62000, 65000, 80000, 50000, 75000, 62000],
    "Experience": [6, 4, 5, 7, 3, 8, 5]
}
df = pd.DataFrame(data)
df.to_csv("employees.csv", index=False)

print("CSV file created successfully!")
!ls

CSV file created successfully!
customer_data.csv  employees.csv  sample_data


In [32]:
df=pd.read_csv("employees.csv")
print("Employees from IT or Finance department")
print(df[df["Department"].isin(['IT', 'Finance'])])
print("---------------------------------------------------")
print("Employees Having Salary > 60,000")
print(df[df["Salary"]>60000])
print("---------------------------------------------------")
print("Employees have at least 5 years of experience")
print(df[df["Experience"]>=5])





Employees from IT or Finance department
   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
2           3    Finance   65000           5
3           4         IT   80000           7
5           6    Finance   75000           8
6           7         IT   62000           5
---------------------------------------------------
Employees Having Salary > 60,000
   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
1           2         HR   62000           4
2           3    Finance   65000           5
3           4         IT   80000           7
5           6    Finance   75000           8
6           7         IT   62000           5
---------------------------------------------------
Employees have at least 5 years of experience
   EmployeeID Department  Salary  Experience
0           1         IT   70000           6
2           3    Finance   65000           5
3           4         IT   80000           7
5           

In [ ]:
'''15. Grouping & Aggregation with Multiple Conditions
Given the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
Task
Find the average salary for each department, but only for employees with at least 5 years of experience.
'''
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT"],
    "Salary": [70000, 50000, 80000, 60000, 52000, 72000, 65000],
    "Experience": [5, 4, 7, 3, 2, 8, 6]
})
df=df[df["Experience"]>=5]
print(df)
print(df.groupby(["Department"])["Salary"].mean())




  Department  Salary  Experience
0         IT   70000           5
2         IT   80000           7
5    Finance   72000           8
6         IT   65000           6
Department
Finance    72000.000000
IT         71666.666667
Name: Salary, dtype: float64


In [ ]:
'''16. NumPy - Complex Indexing
Create a 5x5 NumPy array with random values between 1 and 100.
Write a NumPy command to:
Extract only even numbers from the array.
Extract values from the last row and last column.
Replace all values greater than 50 with 0.
'''
import numpy as np
arr=np.random.randint(1,101,size=(5,5))
print(arr)
print("------------------------------------")
print("Extract only even numbers from the array.")
print(arr[arr%2==0])
print("------------------------------------")
print("Extract values from the last row and last column.")
print(arr[-1,:])
print(arr[:,-1])
print("------------------------------------")
print("Replace all values greater than 50 with 0.")
arr[arr>50]=0
print(arr)




[[ 5 36 44  2 92]
 [23  8 32 59 95]
 [15 35 61 73 62]
 [18 93 56  9 24]
 [27 75 22 94 86]]
------------------------------------
Extract only even numbers from the array.
[36 44  2 92  8 32 62 18 56 24 22 94 86]
------------------------------------
Extract values from the last row and last column.
[27 75 22 94 86]
[92 95 62 24 86]
------------------------------------
Replace all values greater than 50 with 0.
[[ 5 36 44  2  0]
 [23  8 32  0  0]
 [15 35  0  0  0]
 [18  0  0  9 24]
 [27  0 22  0  0]]


In [ ]:
'''17. Matrix Multiplication
Given the two NumPy matrices:
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])
Task
Perform matrix multiplication and output the result.
'''
import numpy as np
A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])

print(A*B)

[[ 2 12]
 [30 56]]


In [ ]:
'''18. Finding Unique & Common Elements
You are given two NumPy arrays:
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
Task
Find the elements that are common in both arrays.
Find the elements that are only present in arr1 but not in arr2.
'''
arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([30, 40, 70, 80, 90])
print("common elements in both array")
print(np.intersect1d(arr1,arr2))
print("--------------------------------------------------")
print("elements that are only present in arr1 but not in arr2")
print(np.setdiff1d(arr1,arr2))


common elements in both array
[30 40]
--------------------------------------------------
elements that are only present in arr1 but not in arr2
[10 20 50 60]


In [ ]:
'''19. Sorting & Ranking in Pandas
You are given the following DataFrame:
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
Task
Sort the players by descending Score.
Assign ranking to each player (1st, 2nd, 3rd...) without skipping numbers.
'''
df = pd.DataFrame({
    "Player": ["A", "B", "C", "D"],
    "Score": [200, 450, 300, 150]
})
df=df.sort_values("Score",ascending=False)
df["Rank"]=range(1,5)
print(df.sort_index())


  Player  Score  Rank
0      A    200     3
1      B    450     1
2      C    300     2
3      D    150     4


In [5]:
# from google.colab import drive
# # Try unmounting first to reset any existing session.
# drive.flush_and_unmount()
# print('Drive unmounted.')

# # Now remount, granting all necessary permissions during the prompt.
# drive.mount('/content/drive', force_remount=True)
# print('Drive mounted successfully!')

# !cp /content/drive/MyDrive/customer_data.csv /content/
!ls

customer_data.csv  sample_data


In [15]:

'''20. Optimizing Pandas Performance
You have a large CSV file ("big_data.csv") with 1 million rows.
Note: You should search & download a large csv file from any portal & use it to perform below tasks
Task
Write optimized Pandas code to:
Load only specific columns: "CustomerID" and "PurchaseAmount".
Load only the first 100,000 rows.
Use an efficient data type for "CustomerID" to save memory.
'''
import pandas as pd
df=pd.read_csv('customer_data.csv')
df=df.head(100000)
df=df[["id","purchase_amount"]]
df['id']=df['id'].astype('int32')
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 2 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               100000 non-null  int32
 1   purchase_amount  100000 non-null  int64
dtypes: int32(1), int64(1)
memory usage: 1.1 MB
