In [ ]:
'''Write a Python program that swaps two numbers without using a third variable.'''
x=10
y=20
print("before swapping:",x,y)
x=x+y
y=x-y
x=x-y
print("After Swapping: ",x,y)

before swapping: 10 20
After Swapping:  20 10


In [ ]:
'''You have a nested list:
data = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a) Extract and print the middle element from the nested list.
b) Flatten the list into a single list [1, 2, 3, 4, 5, 6, 7, 8, 9] without using loops.'''
data = [[1, 2, 3], [4,5,6], [7, 8, 9]]
print(data[1][1])
print([a for x in data for a in x])


5
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
'''3. Tuples - Tuple Unpacking
Given:
values = (100, 200, 300)
a) Unpack this tuple into three variables and print them.
b) Swap the values without using a temporary variable.'''
values = (100, 200, 300)
x,y,z=values
x=x+y
y=x-y
x=x-y
y=y+z
z=y-z
y=y-z
print(x,y,z)


200 300 100


In [ ]:
'''4. Dictionary - Complex Keys
Create a dictionary where:
•   Keys are tuples representing (x, y) coordinates.
•   Values are the sum of x and y.
Example:
{ (1,2): 3, (3,4): 7, (5,6): 11 }
Write a function to retrieve the sum for a given coordinate'''
dict1={(1,2):3,(3,4):7,(5,6):11}
print(dict1)
def retrive_sum(x,y):
  return dict1.get((x,y))
print(retrive_sum(13,2))



{(1, 2): 3, (3, 4): 7, (5, 6): 11}
None


In [ ]:
'''5. Functions - Nested Functions
Write a function outer_function(a, b) that:
•   Contains an inner function to calculate a² + b².
•   Returns the result.
Call outer_function(3, 4) and print the result.'''

def outer_fun(x,y):
  def inner_fun(a,b):
    return (a*a)+(b*b)
  return inner_fun(x,y)
print(outer_fun(2,3))

1


In [ ]:
'''6. Functions - Lambda & Map
You are given a list:
numbers = [1, 2, 3, 4, 5]
Use a lambda function and map() to generate a list where each number is cubed.'''

numbers=[1,2,3,4,5]
# lam=lambda fun: fun*fun*fun
# num_lis=[]
# for i in range(0,len(numbers)):
#   num_lis.append(lam(numbers[i]))
# print(num_lis)


print(list(map(lambda n: n*n*n, numbers)))

[1, 8, 27, 64, 125]


In [ ]:
'''


7. Functions - Recursion
Write a recursive function to
calculate the sum of digits of a given number.
Example:
Input: 1234
Output: 10
(1+2+3+4)'''
def rec_sum(x):
  sum=0
  if(x>9):
    sum+=x%10
    return sum+ rec_sum(int(x/10))
  else:
    return sum+x
ui=int(input("enter a number: "))
print(rec_sum(ui))


enter a number: 2342345
23


In [ ]:
'''8. List Comprehensions
Generate a list of all numbers between 1 and 100 that:
•	Are divisible by 5
•	But not by 3
Use list comprehension.'''
list1=[i for i in range(1,100) if i%5==0 if i%3!=0]
print(list1)

[5, 10, 20, 25, 35, 40, 50, 55, 65, 70, 80, 85, 95]


In [ ]:
'''9. Dictionary - Sorting by Values
Given:
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
Sort this dictionary by values in descending order and print the result'''
scores = {"Alice": 90, "Bob": 85, "Eve": 92}
output = dict(sorted(scores.items(), key=lambda item: item[1], reverse=True))

print(output)

{'Eve': 92, 'Alice': 90, 'Bob': 85}


In [ ]:
'''10. Sets - Unique Characters
Write a Python function that takes a string as input and returns:
•   A set of unique characters in the string.
•   The number of unique characters.
Example:
Input: "hello"
Output: {'h', 'e', 'l', 'o'}, 4'''
def unique_char(str):
  char={}
  for i in str:
    char[i] = char.get(i, 0) + 1
  return  char.keys(),len(char)
print(unique_char("Hello"))

(dict_keys(['H', 'e', 'l', 'o']), 4)


In [ ]:
'''11. Tuples - Finding Common Elements
Given two tuples:
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
Find and print the common elements.'''
t1 = (1, 2, 3, 4, 5)
t2 = (4, 5, 6, 7, 8)
common = tuple(set(t1) & set(t2))
print(common)


(4, 5)


In [ ]:
'''12. Dictionary - Reverse Key-Value Mapping
Given a dictionary:
data = {"A": 1, "B": 2, "C": 3}
Write a program to swap keys and values:
Output: {1: "A", 2: "B", 3: "C"}'''
data = {"A": 1, "B": 2, "C": 3}
new_dict=dict([(value, key) for key, value in data.items()])
print(new_dict)

{1: 'A', 2: 'B', 3: 'C'}


In [ ]:
'''13. Functions - Multiple Return Values
Write a function that takes two numbers as input and returns:
1.  Their sum
2.  Their difference
3.  Their product
4.  Their quotient
Print all four results.'''

def multiple_ret(x,y):
  return x+y, x-y, x*y, int(x/y)

x=int(input("enter first numer: "))
y=int(input("enter second number: "))
print(multiple_ret(x,y))

enter first numer: 6
enter second number: 2
(8, 4, 12, 3)


In [ ]:
'''14. List - Finding Second Largest Number
Write a function to find the second largest number in a given list without using sort().
Example:
Input: [10, 20, 4, 45, 99]
Output: 45'''
data= [10, 20, 4, 45, 99]
max1=max2=data[0]
for i in data:
  if i >max1:
    max2=max1
    max1=i
  elif i > max2 and i != max1:
    max2=i
print(max2)

45


In [ ]:
'''15. List - Pair Sum Problem
Given a list of numbers and a target sum, find all pairs in the list that add up to the target.
Example:
Input: [2, 4, 3, 7, 1, 9], Target: 10
Output: [(3, 7), (1, 9)]'''
list1=[2, 4, 3, 7, 1, 9]
target=10



def pair_sum(num,tg):
  new_list=[]
  for i in range(0,len(num)-1):
    for j in range(i+1,len(num)):
      if((num[i]+num[j])==tg):
        print(num[i],num[j])
        new_list.append((num[i],num[j]))

  return new_list

print(pair_sum(list1,target))

3 7
1 9
[(3, 7), (1, 9)]


In [ ]:
'''16. Pandas - Filtering DataFrame
You are given the following Pandas DataFrame:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
Write a one-liner to filter and display only rows where Age is greater than 25.'''

import pandas as pd
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [24, 27, 22, 32],
    "Score": [85, 90, 78, 88]
})
print( df[df['Age'] > 25] )


    Name  Age  Score
1    Bob   27     90
3  David   32     88


In [ ]:
'''17. Pandas - Group By Operation
You have the following DataFrame:
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
Write a Pandas command to calculate the average salary per department.'''
import pandas as pd
df = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR"],
    "Salary": [70000, 50000, 80000, 60000, 52000]
})
print(df.groupby('Department')['Salary'].mean())


Department
Finance    60000.0
HR         51000.0
IT         75000.0
Name: Salary, dtype: float64


In [ ]:
'''18. NumPy - Create a 5x5 Matrix
Write a program to create a 5x5 NumPy matrix where:
•   The diagonal elements are 1
•   All other elements are 0
Example:
Output:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]'''
import numpy as np

print(np.identity(5, dtype=int)  )

new_list=[]
for i in range(0,5):
  new=[]
  for j in range(0,5):

    if(i==j):
      new.append(1)
    else:
      new.append(0)
    if(j==4):
      new_list.append(new)

print( new_list)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
[[1, 0, 0, 0, 0], [0, 1, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 1, 0], [0, 0, 0, 0, 1]]


In [ ]:
'''19. NumPy - Element-wise Operations
Given two NumPy arrays:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
Perform element-wise:
1.  Addition
2.  Multiplication
3.  Power (a^b)
Print the results.'''
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])
print("Addition:", a+b)
print("Multiplication:", a*b)
print("power:", np.power(a,b))

add=[]
mul=[]
power=[]
for i in range(0,len(a)):
  add.append(a[i]+b[i])
  mul.append(a[i]*b[i])
  power.append(a[i]**b[i])
print("Manual:",add,mul,power)

Addition: [11 22 33 44]
Multiplication: [ 10  40  90 160]
power: [              1         1048576 205891132094649               0]
Manual: [11, 22, 33, 44] [10, 40, 90, 160] [1, 1048576, 205891132094649, 0]


In [ ]:
'''20. NumPy - Find Index of Maximum Value
Given:
arr = np.array([10, 25, 39, 50, 19])
Write a one-liner to find the index of the maximum value.'''
import numpy as np
arr = np.array([10, 25, 39, 50, 19])
print(np.argmax(arr))

3
